CREATE TABLE ITEM(
ID BIGINT AUTO_INCREMENT not null,
ITEM_NAME VARCHAR(50) not null
);

INSERT INTO ITEM (ID, ITEM_NAME) VALUES (0, 'Jajo');
INSERT INTO ITEM (ID, ITEM_NAME) VALUES (1, 'Schoki');
INSERT INTO ITEM (ID, ITEM_NAME) VALUES (2, 'Skarpetka');